name: flutter_navigation
description: A new Flutter project.
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_login: ^4.2.0
  font_awesome_flutter: ^10.5.0
  go_router: ^10.0.0
  shared_preferences: ^2.2.0
  url_strategy: ^0.2.0
  word_generator: ^0.4.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/


  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
